env:
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
overrides:
- files:
  - "**/*.ts"
  extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  parser: "@typescript-eslint/parser"
  plugins:
  - "@typescript-eslint"
  rules:
    "@typescript-eslint/no-explicit-any": 0
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
